"""stac-fastapi-catalogs-extension: Multi-tenant catalog hierarchies for STAC FastAPI."""

from .catalogs import (
    CATALOGS_CORE_CONFORMANCE,
    CATALOGS_SEARCH_CONFORMANCE,
    CATALOGS_TRANSACTION_CONFORMANCE,
    CatalogsExtension,
    CatalogsSearchExtension,
    CatalogsTransactionExtension,
)
from .client import (
    AsyncBaseCatalogsClient,
    AsyncCatalogsSearchClient,
    BaseCatalogsClient,
    BaseCatalogsSearchClient,
)
from .types import (
    CatalogChildrenRequest,
    CatalogCollectionItemsRequest,
    CatalogCollectionItemUri,
    CatalogCollectionsRequest,
    CatalogCollectionUri,
    Catalogs,
    CatalogsGetRequest,
    CatalogsUri,
    Children,
    CreateCatalogCollectionRequest,
    CreateCatalogRequest,
    CreateSubCatalogRequest,
    ObjectUri,
    SubCatalogsRequest,
    UnlinkSubCatalogRequest,
    UpdateCatalogCollectionRequest,
    UpdateCatalogRequest,
)

__all__ = [
    "CatalogsExtension",
    "CatalogsTransactionExtension",
    "CatalogsSearchExtension",
    "AsyncBaseCatalogsClient",
    "AsyncCatalogsSearchClient",
    "BaseCatalogsClient",
    "BaseCatalogsSearchClient",
    "Catalogs",
    "Children",
    "ObjectUri",
    "CATALOGS_CORE_CONFORMANCE",
    "CATALOGS_TRANSACTION_CONFORMANCE",
    "CATALOGS_SEARCH_CONFORMANCE",
    "CatalogsUri",
    "CatalogsGetRequest",
    "CatalogCollectionUri",
    "CatalogCollectionItemUri",
    "CatalogCollectionItemsRequest",
    "CatalogCollectionsRequest",
    "SubCatalogsRequest",
    "CatalogChildrenRequest",
    "CreateCatalogRequest",
    "UpdateCatalogRequest",
    "CreateCatalogCollectionRequest",
    "UpdateCatalogCollectionRequest",
    "CreateSubCatalogRequest",
    "UnlinkSubCatalogRequest",
]
